version: '3.5'

services:
  crawler:
    build:
      context: .
    command: npm start
    ports:
      - 4000:4000
    environment:
      DATABASE_URL: mysql://crawler:crawler@mysql:3306/crawler
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0.15
    ports:
      - 3308:3306
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crawler
      MYSQL_USER: crawler
      MYSQL_PASSWORD: crawler

volumes:
  mysql-volume:
